#!/bin/bash
# https://github.com/twoeightdev
# Author: twoeightdev

me="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
name="$USER"

menu() {
    echo "usage:          " $me "[OPTION]"
    echo " "
    echo "dotfiles:       Git clone dotfiles."
    echo "aurhelper:      Install yay aur helper."
    echo "archpkg:        Install Arch packages."
    echo "aurpkg:         Install AUR packages."
    echo "clean:          Clean up."
}

dotfiles() {
    cd ~
    git clone --bare https://github.com/twoeightdev/archdots.git $HOME/.config/.dots
    git --git-dir=$HOME/.config/.dots/ --work-tree=$HOME checkout
}

aurhelper() {
    cd /tmp/
    curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz
    tar xvzf yay.tar.gz
    cd yay
    makepkg -sci
}

archpkg() {
    # xorg
    pkgs="xorg-server xorg-xdpyinfo xorg-xev xorg-xinit xorg-xinput"
    pkgs="$pkgs xorg-xprop xorg-xset xorg-xsetroot xorg-xwininfo xterm"
    pkgs="$pkgs xcape xclip xdo xdotool xwallpaper"
    # amd
    pkgs="$pkgs lib32-vulkan-radeon mesa-utils mesa-vdpau vulkan-tools"
    # audio
    pkgs="$pkgs pipewire pipewire-alsa pipewire-pulse alsa-utils pulsemixer"
    # fonts
    pkgs="$pkgs libertinus-font noto-fonts noto-fonts-emoji ttf-font-awesome"
    pkgs="$pkgs ttc-iosevka ttc-iosevka-aile ttf-iosevka-nerd ttf-dejavu"
    pkgs="$pkgs ttf-inconsolata ttf-inconsolata-nerd ttf-joypixels"
    pkgs="$pkgs ttf-liberation ttf-roboto-mono"
    # utilities
    pkgs="$pkgs evtest exfat-utils brightnessctl dosfstools gnome-keyring"
    pkgs="$pkgs bc bluez bluez-utils btop ffmpeg ffmpegthumbnailer highlight"
    pkgs="$pkgs htop imagemagick libnotify maim man-db mediainfo moreutils"
    pkgs="$pkgs nvtop ntfs-3g picom poppler psutils ripgrep tree unrar unzip"
    pkgs="$pkgs wget yt-dlp zip tesseract tesseract-data-eng tesseract-data-osd"
    # needed for neovim
    pkgs="$pkgs lua-language-server luarocks npm selene"
    # python
    pkgs="$pkgs python-adblock python-dbus-next python-iwlib python-mpd2"
    pkgs="$pkgs python-pip python-psutil"
    # programs
    pkgs="$pkgs alacritty dunst emacs firefox gimp gucharmap lf newsboat"
    pkgs="$pkgs mpc mpd mpv ncmpcpp nsxiv qtile qutebrowser steam"
    pkgs="$pkgs transmission-cli zathura zathura-pdf-mupdf spotify-launcher"
    # install all listed pkgs
    yay --needed --noconfirm -Syu $pkgs
}

aurpkg() {
    aurpkgs="tremc-git gtk-theme-arc-gruvbox-git"
    yay --needed --noconfirm --answerclean None --answerdiff None --removemake -S $aurpkgs
}

clean() {
    rm -rf /home/$name/.bash_logout
    rm -rf /home/$name/.bash_profile
    rm -rf /home/$name/.bashrc
    rm -rf /home/$name/.zshrc
    mkdir -p /home/$name/.local/downloads
    mkdir -p /home/$name/.local/drafts
    mkdir -p /home/$name/.local/screenshot
    mkdir -p /home/$name/.local/src
    mkdir -p /home/$name/.local/torrent
}


if [ -n "$1" ]; then
    $1
else
    menu
fi
