#+title: Archlinux Post Installation
#+date: <2024-05-10 Fri 15:18>

* Post-installation
** Login
Login as root then =pacman -Syu=

** Enable Multilib
Edit =/etc/pacman.conf/=.
#+begin_src shell
[multilib]
include = /etc/pacman.d/mirrorlist
#+end_src

** Update Repository
#+begin_src shell
pacman -Syu
#+end_src

** Add User
#+begin_src shell
pacman -S zsh
useradd -m -G users,wheel,video,audio,storage,disk -s /bin/zsh twoeightdev
passwd twoeightdev
#+end_src

** Add Sudoers
Edit with =EDITOR=nvim visudo= and uncomment =wheel group=.
#+begin_src shell
%wheel ALL=(ALL) ALL
#+end_src

** User login
Exit =root= and login with your created =USER=.

** Install Dotfiles with Bootstrap Script
#+begin_src shell
curl -LO https://raw.githubusercontent.com/twoeightdev/archdots/main/bootstrap
chmod +x bootstrap
./bootstrap [OPTIONS]
#+end_src

** Install Aur Helper Manually
#+begin_src shell
cd /tmp/
curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz
tar xvzf yay.tar.gz
cd yay
makepkg -sci
#+end_src

** Install Dotfiles Manually
#+begin_src shell
cd ~
git clone --bare https://github.com/twoeightdev/archdots.git $HOME/.config/.dots # Use if https
git clone --bare git@github.com:twoeightdev/archdots.git $HOME/.config/.dots # Use if ssh

git --git-dir=$HOME/.config/.dots/ --work-tree=$HOME checkout
#+end_src

** Touchpad
Enable touch to click. Add the following entries in =/etc/X11/xorg.conf.d/40-libinput.conf=.
#+begin_src shell
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Option "Tapping" "on"
        Driver "libinput"
EndSection
#+end_src

** Root prompt
#+begin_src shell
sudo -i
cp /etc/skel/.bash_profile /root
cp /etc/skel/.bashrc /root

# Change PS1 prompt to my prompt
PS1='\[\e[1;31m\][\u\[\e[1;32m\]@\[\e[1;34m\]\h\[\e[1;35m\] \w\[\e[1;31m]\[\e[0m\]$ '
#+end_src

** Disable Watchdog
Edit or Add entries in =/etc/modprobe.d/watchdog.conf=. or just add kernel parameter to
disable Watchdog.
#+begin_src shell
blacklist iTCO_wdt
blacklist iTCO_vendor_support
#+end_src

** Generate SSH key
#+begin_src shell
cd ~/.ssh
ssh-keygen -t ed25519 -C "your_email@example.com"
#+end_src

** Dotfile SSH remote url
Change dotfiles remote url
#+begin_src shell
dot remote -v
dot remote set-url origin git@github.com:twoeightdev/archdots.git
#+end_src

** Packages
Archpackage and Voidlinux. I'll keep it here just in case i switch back to void.
#+begin_src shell
alacritty - same
alsa-utils - same
amd-ucode - linux-firmware-amd
base - base-devel
base-devel - not needed, one package with base-devel
bc - same
bluez - same
bluez-utils - libspa-bluetooth maybe? -> install this for pipewire users
brightnessctl - same
btop - same
dosfstools - same
dunst - same
emacs - same
evtest - same
exfat-utils - same
ffmpeg - same
ffmpegthumbnailer - same
firefox - same
gimp - same
git - same
gnome-keyring - same
gucharmap - same
highlight - same
htop - same
imagemagick - ImageMagick
lf - same
lib32-vulkan-radeon - mesa-vulkan-radeon-32bit
libertinus-font - not available
libnotify - libnotify
libva-mesa-driver - unknown
linux - same
linux-firmware - same
lua-language-server - same
luarocks - same
maim - same
man-db - same
mediainfo - same
mesa - same
mesa-utils - mesa-demos
mesa-vdpau - same
moreutils - same
mpc - same
mpd - same
mpv - same
ncmpcpp - same
neovim - same
networkmanager - NetworkManager
newsboat - same
noto-fonts - noto-fonts-ttf
noto-fonts-emoji - noto-fonts-emoji
npm - nodejs
nsxiv - same
ntfs-3g - same
nvtop - same
openssh - same
picom - same
pipewire-alsa - alsa-pipewire
pipewire-pulse - unknown
poppler - same
psutils - same
pulsemixer - same
python-adblock - python3-adblock
python-dbus-next - python3-dbus-next
python-iwlib - python3-iwlib
python-mpd2 - python3-mpd2
python-pip - python3-pip
python-psutil - python3-psutil
qtile - same
qutebrowser - same
ripgrep - same
selene - same
spotify
steam
transmission-cli
tree
tremc-git
ttc-iosevka
ttc-iosevka-aile
ttf-dejavu
ttf-font-awesome
ttf-inconsolata
ttf-inconsolata-nerd
ttf-iosevka-nerd
ttf-joypixels
ttf-liberation
ttf-roboto-mono
unrar
unzip
vulkan-radeon
vulkan-tools
wget
xcape
xclip
xdg-user-dirs
xdo
xdotool
xf86-video-amdgpu
xorg-server
xorg-xdpyinfo
xorg-xev
xorg-xinit
xorg-xinput
xorg-xprop
xorg-xset
xorg-xsetroot
xorg-xwininfo
xterm
xwallpaper
yay
yt-dlp
zathura
zathura-pdf-mupdf
zip
zsh
#+end_src
