#+title: Archlinux Post Installation
#+date: <2024-05-10 Fri 15:18>

* Post-installation
** Login
Login as root then =pacman -Syu=

** Enable Multilib
Edit =/etc/pacman.conf/=.
#+begin_src shell
[multilib]
include = /etc/pacman.d/mirrorlist
#+end_src

** Update Repository
#+begin_src shell
pacman -Syu
#+end_src

** Add User
#+begin_src shell
pacman -S zsh
useradd -m -G users,wheel,video,audio,storage,disk -s /bin/zsh twoeightdev
passwd twoeightdev
#+end_src

** Add Sudoers
Edit with =EDITOR=nvim visudo= and uncomment =wheel group=.
#+begin_src shell
%wheel ALL=(ALL) ALL
#+end_src

** User login
Exit =root= and login with your created =USER=.

** Install Dotfiles with Bootstrap Script
Download =bootstrap= script with curl. Do =dot push -u origin main= to push.
#+begin_src shell
curl -LO https://raw.githubusercontent.com/twoeightdev/archdots/main/setup.sh
chmod +x setup.sh
./setup.sh [OPTIONS]
#+end_src

** Install Aur Helper Manually
#+begin_src shell
cd /tmp/
curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz
tar xvzf yay.tar.gz
cd yay
makepkg -sci
#+end_src

** Install Dotfiles Manually
#+begin_src shell
cd ~
git clone --bare https://github.com/twoeightdev/archdots.git $HOME/.config/.dots # Use if https
git clone --bare git@github.com:twoeightdev/archdots.git $HOME/.config/.dots # Use if ssh

git --git-dir=$HOME/.config/.dots/ --work-tree=$HOME checkout
#+end_src

** Touchpad
Enable touch to click. Add the following entries in =/etc/X11/xorg.conf.d/40-libinput.conf=.
#+begin_src shell
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Option "Tapping" "on"
        Driver "libinput"
EndSection
#+end_src

** Root prompt
#+begin_src shell
sudo -i
cp /etc/skel/.bash_profile /root
cp /etc/skel/.bashrc /root

# Change PS1 prompt to my prompt
PS1='\[\e[1;31m\][\u\[\e[1;32m\]@\[\e[1;34m\]\h\[\e[1;35m\] \w\[\e[1;31m]\[\e[0m\]$ '
#+end_src

** Disable Watchdog
Edit or Add entries in =/etc/modprobe.d/watchdog.conf=. or just add kernel parameter to
disable Watchdog.
#+begin_src shell
blacklist iTCO_wdt
blacklist iTCO_vendor_support
#+end_src

** Generate SSH key
#+begin_src shell
cd ~/.ssh
ssh-keygen -t ed25519 -C "your_email@example.com"
#+end_src

** Dotfile SSH remote url
Change dotfiles remote url
#+begin_src shell
dot remote -v
dot remote set-url origin git@github.com:twoeightdev/archdots.git
#+end_src

** Curl Private Repository
Example my /personal token/: =12345abcde=.
#+begin_src shell
curl -s -O https://12345abcde@raw.githubusercontent.com/twoeightdev/reponame/main/file.md
#+end_src
