#+title: Archlinux Post Installation
#+date: <2024-05-10 Fri 15:18>

* Post-installation
** Login
Login as user =twoeightdev= then connect to the internet.

** Update Repository
#+begin_src shell
nmtui
pacman -Syu
#+end_src

** Install Dotfiles with Bootstrap Script
Download =bootstrap= script with curl. Do =dot push -u origin main= to push.
#+begin_src shell
mkdir ~/script
cd ~/script
curl -LO https://raw.githubusercontent.com/twoeightdev/archdots/main/setup.sh
chmod +x setup.sh
./setup.sh [OPTIONS]
./setup.sh aurhelper
./setup.sh archpkg
./setup.sh dotfiles
./setup.sh aurpkg
./setup.sh clean
./setup.sh dmenu
./setup.sh startpage
./setup.sh genkey
./setup.sh remoteurl
#+end_src

** Install Aur Helper Manually
#+begin_src shell
cd /tmp/
curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz
tar xvzf yay.tar.gz
cd yay
makepkg -sci
#+end_src

** Install Dotfiles Manually
#+begin_src shell
cd ~
git clone --bare https://github.com/twoeightdev/archdots.git $HOME/.config/.dots # Use if https
git clone --bare git@github.com:twoeightdev/archdots.git $HOME/.config/.dots # Use if ssh

git --git-dir=$HOME/.config/.dots/ --work-tree=$HOME checkout
#+end_src

** CPU Governor
Check current governor with =cpupower frequency-info= and the result of /current policy:/
is the current governor. Needs kernel paramater =amd_pstate=passive= for this to work.
The default governor for my cpu is =schedutil=. Available frequencies are: =ondemand=,
=conservative=, =userspace=, =powersave=, =performance= and =schedutil=. Default max frequency
is =4.83GHz=. Change governor and max frequency with:
#+begin_src shell
sudo cpupower frequency-set -g ondemand -u 4.0GHz
#+end_src

** Permanent change of CPU Governor and Frequency
Enable service if its not =systemctl enable cpupower.service= Edit =/etc/default/cpupower=,
then uncomment or add:
#+begin_src shell
governor='ondemand'
max_freq="4GHz"
#+end_src

** Disable CPU boost or Turbo Core(AMD)
#+begin_src shell
echo 0 > /sys/devices/system/cpu/cpufreq/boost
#+end_src

** Root prompt
#+begin_src shell
sudo -i
cp /etc/skel/.bash_profile /root
cp /etc/skel/.bashrc /root

# Change PS1 prompt to my prompt
PS1='\[\e[1;31m\][\u\[\e[1;32m\]@\[\e[1;34m\]\h\[\e[1;35m\] \w\[\e[1;31m]\[\e[0m\]$ '
#+end_src

** Generate SSH key
#+begin_src shell
cd ~/.ssh
ssh-keygen -t ed25519 -C "your_email@example.com"
#+end_src

** Dotfile SSH remote url
Change dotfiles remote url
#+begin_src shell
dot remote -v
dot remote set-url origin git@github.com:twoeightdev/archdots.git
#+end_src

** Curl Private Repository
Example my /personal token/: =12345abcde=.
#+begin_src shell
curl -s -O https://12345abcde@raw.githubusercontent.com/twoeightdev/reponame/main/file.md
#+end_src
