# Kanagawa dragon
[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#181616"
foreground = "#c5c9c5"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"

# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"
#
# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"
#
# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"
#
# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"
#
# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
[colors.selection]
text = "#c8c093"
background = "#2d4f67"

[colors.normal]
black = "#0d0c0c"
red = "#c4746e"
green = "#8a9a7b"
yellow = "#c4b28a"
blue = "#8ba4b0"
magenta = "#a292a3"
cyan = "#8ea4a2"
white = "#c8c093"

[colors.bright]
black = "#a6a69c"
red = "#e46876"
green = "#87a987"
yellow = "#e6c384"
blue = "#7fb4ca"
magenta = "#938aa9"
cyan = "#7aa89f"
white = "#c5c9c5"

# [colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#b6927b"

[[colors.indexed_colors]]
index = 17
color = "#b98d7b"

# Last Modified: Fri, 17 Jan 2025 11:59:28 AM
