#!/bin/sh

# xrandr --dpi 144
setbg &
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}"/xorg/xdefaults &
xrdbpid=$!
# /usr/bin/emacs --daemon &
# emacs --daemon &

autostart="picom dunst unclutter remapd"

for program in $autostart; do
    pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

dbus-update-activation-environment --all
dbus-launch ssh-agent qtile start

# Last Modified: Mon, 03 Feb 2025 01:36:42 AM
