live_config_reload = true

# Colors (Tomorrow Night)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

[colors.cursor]
text = '#1d1f21'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[font]
size = 9

[font.normal]
family = "monospace"
style = "medium"

[window]
opacity = 0.95

[window.padding]
x = 20
y = 20
