live_config_reload = true

# [env]
# TERM = "xterm-256color"

# Catppuccin
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[keyboard]
bindings = [
    # { key = "p", mods = "Alt", action = "Paste" },
    # { key = "y", mods = "Alt", action = "Copy" },
    { key = "i", mods = "Alt", action = "ToggleViMode" },
    { key = "k", mods = "Control|Shift", action = "ScrollLineUp" },
    { key = "j", mods = "Control|Shift", action = "ScrollLineDown" },
    { key = "Up", mods = "Control|Alt", action = "ScrollPageUp" },
    { key = "Down", mods = "Control|Alt", action = "ScrollPageDown" },
    { key = "Up", mods = "Control|Shift", action = "ScrollToTop" },
    { key = "Down", mods = "Control|Shift", action = "ScrollToBottom" },
]

[font]
size=9

[font.glyph_offset]
x=0
y=0

[font.offset]
x=0
y=0

[font.normal]
family = "monospace"
style = "Regular"

# [font.italic]
# family = "monospace"
# style = "Italic"
#
# [font.bold]
# family = "monospace"
# style = "Bold"
#
# [font.bold_italic]
# family = "monospace"
# style = "Bold Italic"

[window]
opacity = 0.98

[cursor]
# vi_mode_style = "Beam"
unfocused_hollow = false
thickness = 0.16

[mouse]
hide_when_typing = true

[window.padding]
x = 8
y = 5
