live_config_reload = true

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

[colors.cursor]
text = '#1d2021'
cursor = '#ebdbb2'

# Gruvbox normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Gruvbox bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[keyboard]
bindings = [
    { key = "p", mods = "Alt", action = "Paste" },
    { key = "y", mods = "Alt", action = "Copy" },
    { key = "i", mods = "Alt", action = "ToggleViMode" },
    { key = "k", mods = "Control|Shift", action = "ScrollLineUp" },
    { key = "j", mods = "Control|Shift", action = "ScrollLineDown" },
    { key = "Up", mods = "Control|Alt", action = "ScrollPageUp" },
    { key = "Down", mods = "Control|Alt", action = "ScrollPageDown" },
    { key = "Up", mods = "Control|Shift", action = "ScrollToTop" },
    { key = "Down", mods = "Control|Shift", action = "ScrollToBottom" },
]

[font]
size = 9

[font.normal]
family = "monospace"
style = "Regular"

# [font.italic]
# family = "monospace"
# style = "Italic"
#
# [font.bold]
# family = "monospace"
# style = "Bold"
#
# [font.bold_italic]
# family = "monospace"
# style = "Bold Italic"

[window]
opacity = 0.95

[cursor]
# vi_mode_style = "Beam"
unfocused_hollow = false
thickness = 0.16

[mouse]
hide_when_typing = true

[window.padding]
x = 8
y = 5
